apiVersion: apps/v1
kind: Deployment
metadata:
  name: gomodule1
  labels:
    app: gomodule1
  namespace: namespace-workflow-1684289779500
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gomodule1
  template:
    metadata:
      labels:
        app: gomodule1
    spec:
      containers:
        - name: gomodule1
          image: acrworkflow1684289779500.azurecr.io/image-workflow-1684289779500:latest
          ports:
            - containerPort: 80