apiVersion: v1
kind: Service
metadata:
  name: testfile
  namespace: namespace-workflow-1679344157855
spec:
  type: LoadBalancer
  selector:
    app: testfile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80