apiVersion: v1
kind: Service
metadata:
  name: test1
  namespace: namespace-workflow-1684289981950
spec:
  type: LoadBalancer
  selector:
    app: test1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080